---
deployment:
  tasks:
    - export DEPLOYPATH=/home/varolver/public_html/deneme/menu/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R admin catalog css image img js sound storage system vendor $DEPLOYPATH
    - /bin/cp -f .htaccess favicon.ico index.php robots.txt config.example.php $DEPLOYPATH
